services:
  # proxy:
  #   build: ./proxy
  #   ports:
  #     - "80:8080"
  #   environment:
  #     AUTO_MATE_URL: automate:3000
  automate:
    image: nathan2hao/auto.mate:latest
    volumes:
      - automate-uploads:/app/uploads
    ports:
      - "3000:3000"
  ai:
    image: lobehub/lobe-chat
    ports:
      - "3210:3210"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ACCESS_CODE: ${ASK_ACCESS_CODE}
      OPENAI_MODEL_LIST: "gpt-4o, gpt-4o-mini, gpt-3.5-turbo"
      AI_URL: ai:3210
volumes:
  automate-uploads:

